### ISSUE TITLE
Prototype running on testbed

### ISSUE THREAD

**Issue by Abida16** [pengyanghua/optimus#1]
Hello there,

I am very new to distributed deep learning scheduler implementation. By working with the Optimus framework, I learned about the Hadoop system, Kubernetes cluster setup, docker container, etc. I actually set up all these in EC2 instances. I lack some basic understanding. I am stuck at a point, I am not sure what to do next. What I did is:

1) I set up the Cluster Environment with HDFS, Docker, Kubernetes
2) I installed all the basic tools from [prep_env.sh](https://github.com/pengyanghua/optimus/blob/master/images/gpu/scripts/prep_env.sh)
3) I was working with three NVIDIA GPU instance, so I prepare the CUDA environment
4) For the container environment with mxnet I use the docker script [[k8s-mxnet-gpu-experiment.Dockerfile]](https://github.com/pengyanghua/optimus/blob/master/images/gpu/k8s-mxnet-gpu.Dockerfile) and [build.sh](https://github.com/pengyanghua/optimus/blob/master/images/gpu/build.sh)
5) I set the hyperparameters of [param.py](https://github.com/pengyanghua/optimus/blob/master/scheduler/params.py) according to my environment (the GPU, CPU number, and the IP address of the node list)

At this point, I am confused about how to proceed forward. I run [experimentor.py](https://github.com/pengyanghua/optimus/blob/master/scheduler/experimentor.py) but I am getting the error: 
**command 'kubectl create -f /home/ubuntu/optimus/scheduler/48-experiment-imagenet-vgg-16-2022-10-06-06:28:12/48-experiment-imagenet-vgg-16.yaml' returned non-zero exit status 1.**

And I am also not sure if I am missing any steps(like how to use the [images](https://github.com/pengyanghua/optimus/tree/master/images/gpu/scripts) for running) or misunderstanding parts.

**Comment by pengyanghua** [comment]
@Abida16 Hi, you should examine the exact error message for the command. To get the message, you can run the command in your terminal and observe the error. It may be caused by invalid image URI or invalid data volume path, etc.
